image: node:latest
stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

.default_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

build-job:
  rules:
    - !reference [.default_rules, rules]
  stage: build
  script:
    - npm run build
  artifacts:
    name: "%CI_JOB_STAGE%-%CI_COMMIT_REF_NAME%"
    paths:
      - dist/
  before_script:
    - npm i -g @nestjs/cli
    - npm install

unit-test-job:
  rules:
  - !reference [.default_rules, rules]
  stage: test
  script:
    - npm run test


lint-test-job:
  rules:
  - !reference [.default_rules, rules]
  stage: test
  script:
    - npm run test:cov

deploy-job:
  stage: deploy
  environment: staging
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."