name: learn-github-actions
run-name: ${{ github.actor }} enviou um novo commit
on:
  push:
    branches:
      - develop
      - staging
jobs:
  building_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -g @nestjs/cli
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test