name: learn-github-actions
run-name: ${{ github.actor }} enviou um novo commit
on:
  push:
    branches:
      - develop
      - staging
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: repo-sync/pull-request@v2
        with:
          node-version: 'latest'
          destination_branch: "staging"
          pr_title: "Pulling ${{ github.ref }} into staging"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: "kingdonb"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm i -g @nestjs/cli
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test